# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1004, 701)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.editIP = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editIP.sizePolicy().hasHeightForWidth())
        self.editIP.setSizePolicy(sizePolicy)
        self.editIP.setMaximumSize(QtCore.QSize(150, 16777215))
        self.editIP.setObjectName("editIP")
        self.horizontalLayout_3.addWidget(self.editIP)
        self.editPort = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editPort.sizePolicy().hasHeightForWidth())
        self.editPort.setSizePolicy(sizePolicy)
        self.editPort.setMaximumSize(QtCore.QSize(75, 16777215))
        self.editPort.setObjectName("editPort")
        self.horizontalLayout_3.addWidget(self.editPort)
        self.btnConn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnConn.sizePolicy().hasHeightForWidth())
        self.btnConn.setSizePolicy(sizePolicy)
        self.btnConn.setObjectName("btnConn")
        self.horizontalLayout_3.addWidget(self.btnConn)
        self.btnDisconn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDisconn.sizePolicy().hasHeightForWidth())
        self.btnDisconn.setSizePolicy(sizePolicy)
        self.btnDisconn.setObjectName("btnDisconn")
        self.horizontalLayout_3.addWidget(self.btnDisconn)
        self.labConn = QtWidgets.QLabel(self.centralwidget)
        self.labConn.setMinimumSize(QtCore.QSize(200, 0))
        self.labConn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labConn.setObjectName("labConn")
        self.horizontalLayout_3.addWidget(self.labConn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnTest = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTest.sizePolicy().hasHeightForWidth())
        self.btnTest.setSizePolicy(sizePolicy)
        self.btnTest.setObjectName("btnTest")
        self.horizontalLayout_3.addWidget(self.btnTest)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(140, 130, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 110, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1004, 26))
        self.menubar.setObjectName("menubar")
        self.menuAsset = QtWidgets.QMenu(self.menubar)
        self.menuAsset.setObjectName("menuAsset")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionManagement = QtWidgets.QAction(MainWindow)
        self.actionManagement.setObjectName("actionManagement")
        self.menuAsset.addAction(self.actionManagement)
        self.menubar.addAction(self.menuAsset.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btnConn, self.btnDisconn)
        MainWindow.setTabOrder(self.btnDisconn, self.editIP)
        MainWindow.setTabOrder(self.editIP, self.editPort)
        MainWindow.setTabOrder(self.editPort, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "asset.management"))
        self.editIP.setText(_translate("MainWindow", "127.0.0.1"))
        self.editPort.setText(_translate("MainWindow", "3306"))
        self.btnConn.setText(_translate("MainWindow", "connect"))
        self.btnDisconn.setText(_translate("MainWindow", "disconnect"))
        self.labConn.setText(_translate("MainWindow", "断开"))
        self.btnTest.setText(_translate("MainWindow", "test"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "imput"))
        self.pushButton.setText(_translate("MainWindow", "1111"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.pushButton_2.setText(_translate("MainWindow", "22222"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuAsset.setTitle(_translate("MainWindow", "asset"))
        self.actionManagement.setText(_translate("MainWindow", "management"))

